### ISSUE TITLE
Show Popup 

### ISSUE THREAD

**Issue by azw36** [wbkd/leaflet-swoopy#13]
Popup is not showing. E.g.
`var swoopy = L.swoopyArrow(coords[0], coords[1], {		  
		  color: 'rgba(' + red + "," + green + "," + blue + ",1)",
		  labelFontSize: 12,
		  iconAnchor: [20, 20],
		  iconSize: [20, 20],
		  arrowFilled: false,
		  weight: width
		}); 	
swoopy.bindPopup("test");`
![image](https://user-images.githubusercontent.com/57403292/68215523-aefb3780-ffdf-11e9-8d65-17829250903e.png)

OnClick leaves popupPane empty.

**Comment by moklick** [comment]
hey @azw36,

thanks for reporting the issue! Unfortunately the pop functionality is not supported by the swoopy overlay. Feel free to open a PR if you find a solution.
