### ISSUE TITLE
remove or clear layers

### ISSUE THREAD

**Issue by jakobzhao** [wbkd/leaflet-swoopy#4]
Above all, this library is great!

We have been trying to remove swoopy arrow or clear all swoopy arrows but failed.

I guess your library does not support remove or clearLayers function. Could you please solve this issue?

here is an example: http://geoviz.ceoas.oregonstate.edu/storymap/examples/2.3/swoopy.html
please try to scroll down, and you will see errors popped out.

thank you!

**Comment by jakobzhao** [comment]
@walteral

**Comment by moklick** [comment]
Thanks for the feedback. We will check that

**Comment by stefankeil** [comment]
Should be fixed.

**Comment by jakobzhao** [comment]
Thank you, it works perfectly. refer to http://geoviz.ceoas.oregonstate.edu/storymap/examples/2.3/swoopy.html
try to switch between scene 1 and 2.  @walteral
